monolog:
    handlers:
        main:
            type: stream
            level: 200
            channels: openorchestra
            handler: mongo
        mongo:
            type: mongo
            level: 200
            mongo:
                host: "localhost"
                database: "%open_orchestra_cms.mongodb.database%"
                collection: log
            channels: [openorchestra]
